# Generated by Django 3.0.8 on 2020-07-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPessoa', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.IntegerField()),
                ('acidente', models.CharField(max_length=50)),
                ('likes', models.IntegerField()),
                ('deslikes', models.IntegerField()),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa')),
            ],
        ),
    ]
