# Generated by Django 3.0.8 on 2020-07-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='card',
            name='pessoa',
            field=models.ManyToManyField(to='core.Pessoa'),
        ),
    ]
