# Generated by Django 3.0.8 on 2020-07-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200720_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bairro',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='rua',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
